name: sp_manage_system
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  cached_network_image: ^3.3.0
  http: any
  dio: ^5.4.0
  intl: ^0.19.0
  get: ^4.6.6
  onesignal_flutter: ^5.3.4
  image_picker: ^1.0.4
  carousel_slider: ^4.2.1
  fl_chart: ^0.69.0 
  dropdown_search: ^6.0.1
  flutter_typeahead: ^5.2.0
  open_filex: ^4.0.2
  path_provider: ^2.1.2
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
